### **Naive Bayes Machine Learning Algorithms Implementation**

In [1]:
from sklearn.datasets import load_iris

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
X, y = load_iris(return_X_y=True)

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [6]:
## Since continuous values, using gaussian naive bayes
from sklearn.naive_bayes import GaussianNB

In [7]:
gnb = GaussianNB()

In [8]:
gnb.fit(X_train, y_train)

GaussianNB()

In [9]:
y_pred = gnb.predict(X_test)

In [10]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [11]:
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]

#### Assignment

In [12]:
import seaborn as sns

In [13]:
df = sns.load_dataset('tips')

In [14]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [15]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

Has some numerical and categorical values

Categorical values try to convert into ones and zeros

Try to predict anything, e.g., smoker(binary classification) or time

Take output as time and predict whether it is dinner or lunch

Try it, convert these features into one-hot encoded or label encoded

Said it should be converted into one-hot encoded, think why

One‑Hot Encoding avoids that by creating binary columns for each category:

sex_Female, sex_Male

smoker_Yes, smoker_No  
Each column is independent, so the model learns separate probabilities for each category without assuming order.

In [17]:
import warnings
warnings.filterwarnings('ignore')

In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [19]:
X = df.drop(columns=['time'])
y = df['time']

In [20]:
X

     total_bill   tip     sex smoker   day  size
0         16.99  1.01  Female     No   Sun     2
1         10.34  1.66    Male     No   Sun     3
2         21.01  3.50    Male     No   Sun     3
3         23.68  3.31    Male     No   Sun     2
4         24.59  3.61  Female     No   Sun     4
..          ...   ...     ...    ...   ...   ...
239       29.03  5.92    Male     No   Sat     3
240       27.18  2.00  Female    Yes   Sat     2
241       22.67  2.00    Male    Yes   Sat     2
242       17.82  1.75    Male     No   Sat     2
243       18.78  3.00  Female     No  Thur     2

[244 rows x 6 columns]

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [26]:
X_train.head()

     total_bill   tip     sex smoker  day  size
115       17.31  3.50  Female     No  Sun     2
181       23.33  5.65    Male    Yes  Sun     2
225       16.27  2.50  Female    Yes  Fri     2
68        20.23  2.01    Male     No  Sat     2
104       20.92  4.08  Female     No  Sat     2

In [27]:
ct = ColumnTransformer(transformers=[('onehot', OneHotEncoder(drop='first'), [2, 3, 4])], remainder='passthrough')

In [28]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)
X_train = ct.fit_transform(X_train)

In [29]:
X_test = ct.transform(X_test)

In [30]:
X_train

array([[ 0.  ,  0.  ,  0.  ,  1.  ,  0.  , 17.31,  3.5 ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  , 23.33,  5.65,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  0.  , 16.27,  2.5 ,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 20.23,  2.01,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  , 20.92,  4.08,  2.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 15.01,  2.09,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  7.25,  1.  ,  1.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 26.59,  3.41,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 24.52,  3.48,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 19.77,  2.  ,  4.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 28.15,  3.  ,  5.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  , 17.29,  2.71,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  , 19.65,  3.  ,  2.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 15.53,  3.  ,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 20.45,  3.  ,  4.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  , 34.65,  3.68,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 25.29,  4.71,  4.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 38.01,  3.  ,  4.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  , 29.8 ,  4.2 ,  6.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  9.78,  1.73,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  , 25.71,  4.  ,  3.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 20.08,  3.15,  3.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  , 11.17,  1.5 ,  2.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 38.73,  3.  ,  4.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  , 16.21,  2.  ,  3.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 18.35,  2.5 ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 15.42,  1.57,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 24.06,  3.6 ,  3.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 21.7 ,  4.3 ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 13.94,  3.06,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 29.03,  5.92,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  8.52,  1.48,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  0.  , 16.32,  4.3 ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  1.  ,  0.  , 17.51,  3.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  , 10.29,  2.6 ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 40.17,  4.73,  4.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  , 17.47,  3.5 ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  1.  , 16.58,  4.  ,  2.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 17.92,  3.08,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 17.46,  2.54,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 18.24,  3.76,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  , 15.98,  3.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  , 22.76,  3.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  , 16.43,  2.3 ,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 13.37,  2.  ,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 10.07,  1.25,  2.  ],
       [ 0.  ,  1.  ,  1.  ,  0.  ,  0.  , 13.27,  2.5 ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  , 23.17,  6.5 ,  4.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  1.  , 15.48,  2.02,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  , 16.99,  1.01,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 21.01,  3.5 ,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  , 27.2 ,  4.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 22.23,  5.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  0.  , 11.35,  2.5 ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  , 14.15,  2.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  , 11.87,  1.63,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  , 32.9 ,  3.11,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 28.97,  3.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  , 34.83,  5.17,  4.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 50.81, 10.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 12.66,  2.5 ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 21.01,  3.  ,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 16.31,  2.  ,  3.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  , 27.05,  5.  ,  6.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 13.81,  2.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  , 15.77,  2.23,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  , 12.43,  1.8 ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  , 13.39,  2.61,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  , 10.33,  2.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  , 35.26,  5.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  , 35.83,  4.67,  3.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 12.69,  2.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 14.07,  2.5 ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  , 24.59,  3.61,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  , 14.26,  2.5 ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  , 15.06,  3.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  , 34.3 ,  6.7 ,  6.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  , 31.85,  3.18,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  1.  , 16.  ,  2.  ,  2.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 11.02,  1.98,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  8.51,  1.25,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  , 11.38,  2.  ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 12.16,  2.2 ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  , 40.55,  3.  ,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 12.02,  1.97,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  1.  , 16.47,  3.23,  3.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 17.59,  2.64,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 30.4 ,  5.6 ,  4.  ],
       [ 0.  ,  1.  ,  1.  ,  0.  ,  0.  , 30.14,  3.09,  4.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 16.04,  2.24,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  , 15.95,  2.  ,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 39.42,  7.58,  4.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  , 45.35,  3.5 ,  3.  ],
       [ 0.  ,  1.  ,  0.  ,  1.  ,  0.  ,  9.6 ,  4.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  , 16.66,  3.4 ,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 31.27,  5.  ,  3.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  1.  , 20.53,  4.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 32.4 ,  6.  ,  4.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  , 22.75,  3.25,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 20.69,  5.  ,  5.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  9.68,  1.32,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  8.35,  1.5 ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  , 15.69,  1.5 ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 23.68,  3.31,  2.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 15.36,  1.64,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  9.94,  1.56,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  , 12.26,  2.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  0.  , 13.42,  3.48,  2.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 32.83,  1.17,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  0.  , 10.09,  2.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 18.04,  3.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 13.81,  2.  ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  1.  , 19.44,  3.  ,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 17.78,  3.27,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  1.  , 12.74,  2.01,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 26.88,  3.12,  4.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 15.81,  3.16,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 14.  ,  3.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  0.  , 22.49,  3.5 ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  1.  , 32.68,  5.  ,  2.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 11.59,  1.5 ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  8.58,  1.92,  1.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  , 21.16,  3.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 15.04,  1.96,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 18.43,  3.  ,  4.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 48.27,  6.73,  4.  ],
       [ 0.  ,  1.  ,  1.  ,  0.  ,  0.  , 12.76,  2.23,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  , 20.27,  2.83,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 16.29,  3.71,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 20.76,  2.24,  2.  ],
       [ 0.  ,  1.  ,  1.  ,  0.  ,  0.  , 26.86,  3.14,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 11.61,  3.39,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  , 18.26,  3.25,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  1.  , 13.51,  2.  ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 13.42,  1.58,  2.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 18.29,  3.76,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 25.56,  4.34,  4.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 25.21,  4.29,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 12.54,  2.5 ,  2.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 24.01,  2.  ,  4.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  , 16.82,  4.  ,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 48.33,  9.  ,  4.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  , 23.1 ,  4.  ,  3.  ],
       [ 0.  ,  1.  ,  1.  ,  0.  ,  0.  , 27.18,  2.  ,  2.  ],
       [ 0.  ,  1.  ,  1.  ,  0.  ,  0.  , 12.9 ,  1.1 ,  2.  ],
       [ 0.  ,  1.  ,  1.  ,  0.  ,  0.  , 10.63,  2.  ,  2.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 11.24,  1.76,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 28.55,  2.05,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  , 24.71,  5.85,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  , 20.29,  2.75,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  , 26.41,  1.5 ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  1.  , 16.4 ,  2.5 ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 21.5 ,  3.5 ,  4.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 12.6 ,  1.  ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  , 30.46,  2.  ,  5.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  1.  , 19.81,  4.19,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  , 22.82,  2.18,  3.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  , 16.93,  3.07,  3.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  , 25.  ,  3.75,  4.  ],
       [ 0.  ,  1.  ,  1.  ,  0.  ,  0.  , 22.12,  2.88,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 10.34,  1.66,  3.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  , 34.81,  5.2 ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  7.51,  2.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  , 19.08,  1.5 ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 13.13,  2.  ,  2.  ],
       [ 0.  ,  1.  ,  1.  ,  0.  ,  0.  , 22.42,  3.48,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  0.  , 12.46,  1.5 ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  , 29.93,  5.07,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  , 18.28,  4.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  1.  , 13.  ,  2.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  , 14.73,  2.2 ,  2.  ],
       [ 0.  ,  1.  ,  1.  ,  0.  ,  0.  , 28.17,  6.5 ,  3.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 30.06,  2.  ,  3.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  , 13.42,  1.68,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  , 18.78,  3.  ,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 17.92,  4.08,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  1.  ,  0.  , 18.15,  3.5 ,  3.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  , 17.07,  3.  ,  3.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  , 20.49,  4.06,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  , 14.83,  3.02,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  5.75,  1.  ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  , 34.63,  3.55,  2.  ],
       [ 0.  ,  1.  ,  1.  ,  0.  ,  0.  , 44.3 ,  2.5 ,  3.  ]])

In [31]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [32]:
gnb.fit(X_train, y_train)

GaussianNB()

In [33]:
y_pred = gnb.predict(X_test)

In [34]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.9508196721311475
              precision    recall  f1-score   support

      Dinner       1.00      0.93      0.96        44
       Lunch       0.85      1.00      0.92        17

    accuracy                           0.95        61
   macro avg       0.93      0.97      0.94        61
weighted avg       0.96      0.95      0.95        61

[[41  3]
 [ 0 17]]